const query = [
  {
    ask: "면보다 밥? 밥보다 면? 당신의 선택은..!",
    answer: [{ a: "a. 면" }, { b: "b. 밥" }, { c: "c. 글쎄..." }],
    index: 0,
  },
  {
    ask: "나는 맵찔이ㅠ_ㅠ",
    answer: [{ a: "a. 맞다" }, { b: "b. 아니다" }],
    index: 1,
  },
  {
    ask: "국물이 땡긴다, 안 땡긴다?",
    answer: [{ a: "a. 땡김" }, { b: "b. 안 땡김" }],
    index: 2,
  },
  {
    ask: "나는 크림파? 토마토파?",
    answer: [
      { a: "a. 크림파!" },
      { b: "b. 토마토파!" },
      { c: "c. 못 고르겠어ㅠ_ㅠ" },
    ],
    index: 3,
  },
];
const foodList = [
  {
    name: "칼국수",
    words: "뜨뜻한 칼국수와 겉절이의 조합은 최고!",
    img: "img/noodle.png",
    type: "한식",
    data: ["a", "a"],
  },
  {
    name: "비빔냉면",
    words: "물냉보단 비냉이지~!",
    img: "img/noodle.png",
    type: "한식",
    data: ["a", "b"],
  },
  {
    name: "순대국밥",
    words: "겨울엔 뜨뜻한 국밥 한그릇이 최고",
    img: "img/soup.png",
    type: "한식",
    data: ["b", "a"],
  },
  {
    name: "제육볶음",
    words: "빨간양념 고기와 밥의 조합 최고",
    img: "img/meat1.png",
    type: "한식",
    data: ["b", "b"],
  },
  {
    name: "전골",
    words: "뜨끈한 국물에 빠진 고기와 만두를 골라먹는 재미...!",
    img: "img/hot-pot.png",
    type: "한식",
    data: ["c", "a"],
  },
  {
    name: "삼겹살",
    words: "고기 이즈 뭔들~",
    img: "img/meat2.png",
    type: "한식",
    data: ["c", "b"],
  },
  {
    name: "잔치국수",
    words: "잔치국수 먹으면서 잔치 열자!",
    img: "img/noodle.png",
    type: "한식",
  },
  {
    name: "물냉면",
    words: "여름을 느끼고 싶을 땐 물냉면~",
    img: "img/noodle.png",
    type: "한식",
  },
  {
    name: "소불고기",
    words: "점잖은 소불고기 먹고 오늘 하루도 화이팅~",
    img: "img/meat1.png",
    type: "한식",
  },
  {
    name: "육개장",
    words: "역시 따뜻한 국물은 육개장...!",
    img: "img/soup.png",
    type: "한식",
  },
  {
    name: "설렁탕",
    words: "해장하기 딱 좋은 설렁탕~~~",
    img: "img/soup.png",
    type: "한식",
  },
  {
    name: "까르보나라",
    words: "파스타의 정석",
    img: "img/pasta2.png",
    type: "양식",
    data: ["a", "a"],
  },
  {
    name: "스파게티",
    words: "기본 중의 기본 스파게뤼~~",
    img: "img/pasta1.png",
    type: "양식",
    data: ["a", "b"],
  },
  {
    name: "로제파스타",
    words: "크림과 토마토 둘 다 잡자!",
    img: "img/pasta3.png",
    type: "양식",
    data: ["a", "c"],
  },
  {
    name: "베이컨크림리조또",
    words: "만인의 사랑 베이컨이 들어간...!",
    img: "img/risotto.png",
    type: "양식",
    data: ["b", "a"],
  },
  {
    name: "해물토마토리조또",
    words: "해물과 빨간 소스의 조화...!",
    img: "img/risotto.png",
    type: "양식",
    data: ["b", "b"],
  },
  {
    name: "치킨로제리조또",
    words: "치킨과 빨간 소스의 조화...!",
    img: "img/risotto.png",
    type: "양식",
    data: ["b", "c"],
  },
  {
    name: "베이컨크림 감자뇨끼",
    words: "부드럽고 쫀득쫀득한 뇨끼!",
    img: "img/gnocchi.png",
    type: "양식",
    data: ["c", "a"],
  },
  {
    name: "페퍼로니 피자",
    words: "토마토 소스와 치즈의 조합!",
    img: "img/pizza.png",
    type: "양식",
    data: ["c", "b"],
  },
  {
    name: "샌드위치",
    words: "한 끼는 가볍게 먹어줘야지~",
    img: "img/sandwich.png",
    type: "양식",
    data: ["c", "c"],
  },
  {
    name: "우동",
    words: "따뜻한 국물이 땡길 땐~",
    img: "img/noodle1.png",
    type: "일식",
    data: ["a", "a"],
  },
  {
    name: "냉모밀",
    words: "시원하게 즐기기엔 냉모밀이 최고!",
    img: "img/noodle.png",
    type: "일식",
    data: ["a", "b"],
  },
  {
    name: "돈까스",
    words: "바삭바삭 내 사랑 돈까스",
    img: "img/tonkatsu.png",
    type: "일식",
    data: ["b", "a"],
  },
  {
    name: "초밥",
    words: "초밥 이즈 사랑",
    img: "img/sushi.png",
    type: "일식",
    data: ["b", "b"],
  },
  {
    name: "오코노미야키",
    words: "이번엔 오코노미야키 맛집을 가보자!",
    img: "img/okonomiyaki.png",
    type: "일식",
    data: ["c", "a"],
  },
  {
    name: "모둠 사시미",
    words: "참치, 연어 등 각종 신선한 해산물을 즐겨~",
    img: "img/sashimi.png",
    type: "일식",
    data: ["c", "b"],
  },
  {
    name: "라멘",
    words: "라면과는 확실히 다른 매력...!",
    img: "img/noodle2.png",
    type: "일식",
  },
  {
    name: "규동",
    words: "고기 얹어진 밥이 맛이 없을수가 없쥬~",
    img: "img/donburi.png",
    type: "일식",
  },
  {
    name: "연어덮밥",
    words: "연어 이즈 뭔들",
    img: "img/salmon.png",
    type: "일식",
  },
  {
    name: "짜장면",
    words: "중식은 역시 짜장면",
    img: "img/jajangmyeon.png",
    type: "중식",
    data: ["a", "a"],
  },
  {
    name: "짬뽕",
    words: "얼큰한 짬뽕~",
    img: "img/noodle1.png",
    type: "중식",
    data: ["a", "b"],
  },
  {
    name: "새우볶음밥",
    words: "볶음밥은 맛없없",
    img: "img/friedrice.png",
    type: "중식",
    data: ["b", "a"],
  },
  {
    name: "마라샹궈",
    words: "엄청나게 자극적인 맛! 밥과 함께 즐기세요",
    img: "img/soup.png",
    type: "중식",
    data: ["b", "b"],
  },
  {
    name: "양꼬치",
    words: "삼겹살, 소고기 말고 양꼬치!",
    img: "img/meat2.png",
    type: "중식",
    data: ["c", "a"],
  },
  {
    name: "마라탕",
    words: "빨간 국물에 빠진 각종 채소들을 즐기고 싶을 땐...!",
    img: "img/soup.png",
    type: "중식",
    data: ["c", "b"],
  },
];
